### ISSUE TITLE
Env settings don't work if there's no tag or if no tagged build exists on gitlab

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/solas-chart#12]
This may be a failfast-ci bug, but the idea that we have to create a dummy tag in order to even do the first ci build seems less-than-ideal. To work around this I moved the environment variable setting and Chart.yaml build to a [build.sh script](https://github.com/samsung-cnct/chart-failfast-ci/blob/master/build/build.sh). This allows it to always succeed in building a Chart.yaml that will pass helm linting even if there hasn't been a tag yet.

**Comment by guineveresaenger** [comment]
Included in https://github.com/samsung-cnct/solas-chart/pull/14

**Comment by guineveresaenger** [comment]
ToReview:
Ensure this concern was addressed in https://github.com/samsung-cnct/solas-chart/pull/14
