### ISSUE TITLE
Just call the scripts directly

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/solas-chart#13]
https://github.com/samsung-cnct/solas-chart/blob/7a6d5d7d4713d406ed9daee2a7556285deeee901/.gitlab-ci.yml#L44 calls a script using sh. The script's shebang requests bash.

Just make the script executable, set the shebang for the shell we want to use (/bin/sh is safest) and call the script, ie. `- build/test.sh`.

**Comment by guineveresaenger** [comment]
Fixed by https://github.com/samsung-cnct/solas-chart/pull/14
