### ISSUE TITLE
make this pass CI

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/solas-chart#19]
since this is our template , it would be great if it would pass gitlab CI. It is hard to know if changes made to the gitlab files are going to work if they aren't passing tests in the template.
When complete, please check off `solas-chart` on https://github.com/samsung-cnct/issues/issues/89#issuecomment-343000090

**Comment by leahnp** [comment]
Merged: https://github.com/samsung-cnct/solas-chart/pull/20
