### ISSUE TITLE
Create CI template for gitlab

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/solas-chart#8]
Create a .gitlab-ci.yml for charts

Helpful samples:
https://github.com/samsung-cnct/cyklops-events/pull/7/files
https://git.cnct.io/venezia/install-mongodb/blob/master/.gitlab-ci.yml
https://github.com/joejulian/chart-ingress-nginx/pull/1/files (chart specific example)

**Comment by guineveresaenger** [comment]
For research purposes, I will attempt to create gitlab CI on https://github.com/samsung-cnct/chart-fluent-bit first, before creating a template.

**Comment by guineveresaenger** [comment]
ToReview:

Review example implementation: https://github.com/samsung-cnct/chart-fluent-bit/pull/13
Also https://github.com/samsung-cnct/solas-chart/pull/9

Note that the example implementation demonstrates a Cleanup stage; more detail is outlined in [this PR.}(https://github.com/samsung-cnct/solas/pull/33/files#diff-e92fba9f5224171ba640825efbb249a9R81)

**Comment by leahnp** [comment]
Fixed by: https://github.com/samsung-cnct/solas-chart/pull/9
